name: Docker Build and Push

on:
  push:
    branches: [main]
    paths:
      - "messaging_app/**"
      - "!messaging_app/.github/**"
  pull_request:
    branches: [main]
    paths:
      - "messaging_app/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/messaging_app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/messaging_app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/messaging_app:buildcache,mode=max

      - name: Image digest
        run: |
          echo "Image digest: ${{ steps.docker_build.outputs.digest }}"
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'
